function generateGoogleSearchQuery(targetDomain, type) {
    if (!targetDomain) throw new Error('Target domain is required');
    let searchQuery = 'site:' + targetDomain;
    switch (type) {
        case 'index-of': searchQuery += ' intitle:index.of'; break;
        case 'config-files': searchQuery += ' ext:xml | ext:conf | ext:cnf | ext:reg | ext:inf | ext:rdp | ext:cfg | ext:txt | ext:ora | ext:ini'; break;
        case 'database-files': searchQuery += ' ext:sql | ext:dbf | ext:mdb'; break;
        case 'log-files': searchQuery += ' ext:log'; break;
        case 'backup': searchQuery += ' ext:bkf | ext:bkp | ext:bak | ext:old | ext:backup'; break;
        case 'login': searchQuery += ' inurl:login'; break;
        case 'sql-errors': searchQuery += ' intext:"sql syntax near" | intext:"syntax error has occurred" | intext:"incorrect syntax near" | intext:"unexpected end of SQL command" | intext:"Warning: mysql_connect()" | intext:"Warning: mysql_query()" | intext:"Warning: pg_connect()"'; break;
        case 'documents': searchQuery += ' ext:doc | ext:docx | ext:odt | ext:pdf | ext:rtf | ext:sxw | ext:psw | ext:ppt | ext:pptx | ext:pps | ext:csv'; break;
        case 'phpinfo': searchQuery += ' ext:php intitle:phpinfo "published by the PHP Group"'; break;
        case 'wordpress': searchQuery += ' inurl:wp- | inurl:wp-content | inurl:plugins | inurl:uploads | inurl:themes | inurl:download'; break;
        case 'shell-backdoor': searchQuery += ' inurl:shell | inurl:backdoor | inurl:wso | inurl:cmd | shadow | passwd | boot.ini | inurl:backdoor'; break;
        case 'readme-install': searchQuery += ' inurl:readme | inurl:license | inurl:install | inurl:setup | inurl:config'; break;
        case 'redirect': searchQuery += ' inurl:redir | inurl:url | inurl:redirect | inurl:return | inurl:src=http | inurl:r=http'; break;
        case 'struts': searchQuery += ' ext:action | ext:struts | ext:do'; break;
        case 'pastebin': return 'https://www.google.com/search?q=' + encodeURIComponent('site:pastebin.com ' + targetDomain);
        case 'linkedin': return 'https://www.google.com/search?q=' + encodeURIComponent('site:linkedin.com employees ' + targetDomain);
        case 'phpinfo-htaccess': return 'https://www.google.com/search?q=' + encodeURIComponent('inurl:"/phpinfo.php" | inurl:".htaccess" | inurl:"/.git" ' + targetDomain + ' -github');
        case 'subdomains': return 'https://www.google.com/search?q=' + encodeURIComponent('site:*.' + targetDomain);
        case 'sub-subdomains': return 'https://www.google.com/search?q=' + encodeURIComponent('site:*.*.' + targetDomain);
        case 'wp-includes': return 'https://www.google.com/search?q=' + encodeURIComponent('inurl:wp-content | inurl:wp-includes ' + targetDomain);
        case 'github': return 'https://github.com/search?q=' + encodeURIComponent('".' + targetDomain + '"') + '&type=host';
        case 'crossdomain': return 'http://' + targetDomain + '/crossdomain.xml';
        case 'threatcrowd': return 'http://threatcrowd.org/domain.php?domain=' + targetDomain;
        case 'swf-google': return 'https://www.google.com/search?q=' + encodeURIComponent('+inurl:' + targetDomain + ' +ext:swf');
        case 'swf-yandex': return 'https://yandex.com/search/?text=' + encodeURIComponent('site:' + targetDomain + ' mime:swf');
        case 'swf-archive': return 'https://web.archive.org/cdx/search?url=' + encodeURIComponent(targetDomain) + '/&matchType=domain&collapse=urlkey&output=text&fl=original&filter=urlkey:.*swf&limit=100000';
        case 'swf-mime-archive': return 'https://web.archive.org/cdx/search?url=' + encodeURIComponent(targetDomain) + '/&matchType=domain&collapse=urlkey&output=text&fl=original&filter=mimetype:application/x-shockwave-flash&limit=100000';
        case 'archive-domain': return 'https://web.archive.org/web/*/(.' + encodeURIComponent('.' + targetDomain) + ')';
        case 'archive-wildcard': return 'https://web.archive.org/web/*/' + encodeURIComponent(targetDomain) + '/*';
        case 'crt-sh': return 'https://crt.sh/?q=%25.' + targetDomain;
        case 'openbugbounty': return 'https://www.openbugbounty.org/search/?search=' + encodeURIComponent(targetDomain) + '&type=host';
        case 'reddit': return 'https://www.reddit.com/search/?q=' + encodeURIComponent(targetDomain) + '&source=recent';
        case 'wordpress-archive': return 'http://wwwb-dedup.us.archive.org:8083/cdx/search?url=' + encodeURIComponent('+inurl:' + targetDomain + ' +ext:wp- | +inurl:' + targetDomain + ' +ext:wp-content') + '/&matchType=domain&collapse=digest&output=text&fl=original,timestamp&filter=urlkey:.*wp[-].*&limit=1000000';
        case 'censys-ipv4': return 'https://censys.io/ipv4?q=' + targetDomain;
        case 'censys-domain': return 'https://censys.io/domain?q=' + targetDomain;
        case 'censys-certificates': return 'https://censys.io/certificates?q=' + targetDomain;
        case 'shodan': return 'https://www.shodan.io/search?query=' + targetDomain;
        case 'geoserver-wfs': searchQuery += ' inurl:"/geoserver/ows?service=wfs"'; break;
        case 'arcgis': searchQuery += ' intext:"ArcGIS REST Services Directory" intitle:"Folder: /"'; break;
        case 'wp-wcpdf': searchQuery += ' inurl:/wp-content/uploads/wpo_wcpdf'; break;
        case 'main-yml': searchQuery += ' intitle:"index of "main.yml"'; break;
        case 'admin-aspx': searchQuery += ' inurl:/admin.aspx'; break;
        case 'wp-wcpdf-upload': searchQuery += ' inurl:/wp-content/uploads/wpo_wcpdf'; break;
        case 'uploadimage': searchQuery += ' inurl:uploadimage.php'; break;
        case 'contact-form-7': searchQuery += ' inurl:*/wp-content/plugins/contact-form-7/'; break;
        case 'conf-php': searchQuery += ' intitle:index.of conf.php'; break;
        case 'sharing-api': searchQuery += ' intitle:"Sharing API Info"'; break;
        case 'admin-zip': searchQuery += ' intitle:"Index of" inurl:/backup/ "admin.zip"'; break;
        case 'github-api': searchQuery += ' intitle:"index of" github-api'; break;
        case 'wp-wcpa': searchQuery += ' inurl:wp-content/uploads/wcpa_uploads'; break;
        case 'drupal-login': searchQuery += ' inurl:user intitle:"Drupal" intext:"Log in" -"powered by"'; break;
        case 'joomla-database': searchQuery += ' inurl: /libraries/joomla/database/'; break;
        case 'sql-select': searchQuery += ' inurl:"php?sql=select" ext:php'; break;
        case 'wp-config': searchQuery += ' inurl:"wp-content" intitle:"index.of" intext:wp-config.php'; break;
        case 'json-rpc': searchQuery += ' intext:"index of" inurl:json-rpc'; break;
        case 'download-php': searchQuery += ' intitle:"index of" "download.php?file="'; break;
        case 'jwks-rsa': searchQuery += ' intext:"index of" inurl:jwks-rsa'; break;
        case 'wp-backup': searchQuery += ' inurl:"wp-content" intitle:"index.of" intext:backup"'; break;
        case 'conf-mysql': searchQuery += ' intitle:index.of conf.mysql'; break;
        case 'yaml-config': searchQuery += ' intitle:"index of" "users.yml" | "admin.yml" | "config.yml"'; break;
        case 'docker-compose': searchQuery += ' intitle:"index of" "docker-compose.yml"'; break;
        case 'pom-xml': searchQuery += ' intext:pom.xml intitle:"index of /"'; break;
        case 'etc-index': searchQuery += ' intext:"Index of" intext:"/etc"'; break;
        case 'sql-parent': searchQuery += ' "sql" "parent" intitle:index.of -injection'; break;
        default: throw new Error('Invalid feature selected');
    }
    return 'https://www.google.com/search?q=' + encodeURIComponent(searchQuery);
}

module.exports = { generateGoogleSearchQuery };
